monolog:
    channels: ['exchange_rates', 'binance_api', 'scheduler']
    
    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            channels: ['!event']
        
        # Dedicated log file for exchange rates operations
        exchange_rates:
            type: stream
            path: '%kernel.logs_dir%/exchange_rates.log'
            level: debug
            channels: ['exchange_rates']
            formatter: monolog.formatter.json
        
        # Dedicated log file for Binance API calls
        binance_api:
            type: stream
            path: '%kernel.logs_dir%/binance_api.log'
            level: debug
            channels: ['binance_api']
            formatter: monolog.formatter.json
        
        # Scheduler operations
        scheduler:
            type: stream
            path: '%kernel.logs_dir%/scheduler.log'
            level: debug
            channels: ['scheduler']
            formatter: monolog.formatter.json
        
        # Console output for development
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!console']
        
        # Browser-based logging for debugging
        browser_console:
            type: browser_console
            level: debug
